version: "3.6"
services:
  gitlab:
    restart: always
    image: gitlab/gitlab-ce:latest
    ports:
      - "30022:22"
      - "30080:80"
      - "30443:443"
    volumes:
      - ./data:/var/opt/gitlab
      - ./logs:/var/log/gitlab
      - ./config:/etc/gitlab
    depends_on:
      - redis
      - postgresql
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        postgresql['enable'] = false
        gitlab_rails['db_username'] = "gitlab"
        gitlab_rails['db_password'] = "gitlab"
        gitlab_rails['db_host'] = "postgresql"
        gitlab_rails['db_port'] = "5432"
        gitlab_rails['db_database'] = "gitlabhq_production"
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = '6379'
        external_url 'http://localhost/'
        gitlab_rails['time_zone'] = 'Asia/Tokyo'
        gitlab_rails['gitlab_shell_ssh_port'] = 30022

  gitlab-runner:
    restart: always
    image: gitlab/gitlab-runner:alpine
    depends_on:
      - gitlab
    volumes:
      - ./gitlab_ci/runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    restart: always
    image: redis:3.0.7-alpine
    command:
      - --loglevel warning
    volumes:
      - ./redis:/var/lib/redis

  postgresql:
    restart: always
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=gitlab
      - POSTGRES_PASSWORD=gitlab
      - POSTGRES_DB=gitlabhq_production
    volumes:
      - ./postgresql:/var/lib/postgresql
