version: "3.6"
services:
  redis:
    image: redis:5.0.7-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ../redis/data:/data:Z
      - ../conf/redis/redis.conf:/usr/local/etc/redis/redis.conf

  postgresql:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=gitlab
      - POSTGRES_PASSWORD=gitlab
      - POSTGRES_DB=gitlabhq_production
    volumes:
      - ../postgresql/data:/var/lib/postgresql/data:Z

  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "30022:22"
    volumes:
      - ../data:/var/opt/gitlab:Z
      - ../logs:/var/log/gitlab:Z
      - ../config:/etc/gitlab:Z
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    command: /bin/bash -c "sleep 20 && /assets/wrapper"
    configs:
      - source: gitlab
        target: /omnibus_config.rb

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    volumes:
      - ../gitlab-runner:/etc/gitlab-runner:Z
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 2

  nginx:
    image: nginx:1.13
    depends_on:
      - gitlab
    ports:
      - "80:80"
      - "443:443"
    command: /bin/bash -c "sleep 300 && nginx -g 'daemon off;'"
    volumes:
      - ../conf/nginx/:/etc/nginx/

configs:
  gitlab:
    file: ./gitlab.rb
