version: "3.7"
services:
  redis:
    image: redis:5.0.7-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ../redis/data:/data:Z
      - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - private
    deploy:
      update_config:
        parallelism: 1
        delay: 1s
        order: start-first
      placement:
        constraints:
          - node.role == manager

  postgresql:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=gitlab
      - POSTGRES_PASSWORD=gitlab
      - POSTGRES_DB=gitlabhq_production
    volumes:
      - ../postgresql/data:/var/lib/postgresql/data:Z
    networks:
      - private
    deploy:
      update_config:
        parallelism: 1
        delay: 1s
        order: start-first
      placement:
        constraints:
          - node.role == manager

  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "30022:22"
    command: /bin/bash -c "sleep 15 && /assets/wrapper"
    volumes:
      - ../data:/var/opt/gitlab:Z
      - ../logs:/var/log/gitlab:Z
      - ../config:/etc/gitlab:Z
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    networks:
      - private
    deploy:
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
      placement:
        constraints:
          - node.role == manager

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    volumes:
      - ../gitlab-runner:/etc/gitlab-runner:Z
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - private
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == worker

  nginx:
    image: nginx:1.13
    depends_on:
      - gitlab
    ports:
      - "80:80"
      - "443:443"
    command: /bin/bash -c "sleep 240 && nginx -g 'daemon off;'"
    volumes:
      - ./conf/nginx/:/etc/nginx/
    networks:
      - private
    deploy:
      update_config:
        parallelism: 1
        delay: 1s
        order: start-first
      placement:
        constraints:
          - node.role == manager

configs:
  gitlab:
    file: ./gitlab.rb

networks:
  private:
    driver: overlay
    internal: true
    attachable: true
  public:
    driver: overlay
    attachable: true
